<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Dashboard</title>
	<link rel="stylesheet" href="dashboard/assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="dashboard/assets/css/app.css">
</head>
<body>

	<nav class="navbar navbar-default" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/dashboard">Dashboard</a>
			</div>
	
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="nav navbar-nav">
					&nbsp;
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">User <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="#">Account</a></li>
							<li><a href="#">Logout</a></li>
						</ul>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div>
	</nav>

	<div class="container">
		<ol class="breadcrumb">
			<li>
				<a href="/dashboard">Home</a>
			</li>
			<li class="active">Dashboard</li>
		</ol>

		<div role="tabpanel">
			<!-- Nav tabs -->
			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active">
					<a href="#dashboard" aria-controls="dashboard" role="tab" data-toggle="tab">Dashboard</a>
				</li>
				<li role="presentation">
					<a href="#announcements" aria-controls="announcements" role="tab" data-toggle="tab">Announcements</a>
				</li>
			</ul>
		
			<!-- Tab panes -->
			<div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="dashboard">
					<h1>Dashboard</h1>
				</div>
				<div role="tabpanel" class="tab-pane" id="announcements">
					<h1>Announcements</h1>

					<div class="table-responsive">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Title</th>
									<th>Content</th>
									<th>Edit</th>
									<th>Delete</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td></td>
								</tr>
							</tbody>
						</table>
					</div>

					<a class="btn btn-primary" data-toggle="modal" href='#add-announcement'>Create</a>
					<div class="modal fade" id="add-announcement">
						<div class="modal-dialog">
							<form action="/dashboard/announcements" method="POST">
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
										<h4 class="modal-title">Create Announcement</h4>
									</div>
									<div class="modal-body">
										<div class="form-group">
											<label for="title">Title</label>
											<input type="text" name="title" id="title" class="form-control" required>
										</div>
										<div class="form-group">
											<label for="file">File</label>
											<input type="file" name="file" id="file" required>
										</div>
									</div>
									<div class="modal-footer">
										<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
										<button type="submit" class="btn btn-primary">Submit</button>
									</div>
								</div>
							</form>
						</div>
					</div>


				</div>
			</div>
		</div>

	</div>


	<footer>
		<div class="container text-center">
			<h4>Bulongwa Health Sciences Institute</h4>
			<p>&copy; <?=date('Y')?> All Rights Reserved</p>
		</div>
	</footer>
	
	<script src="dashboard/assets/js/jquery.min.js"></script>
	<script src="dashboard/assets/js/bootstrap.min.js"></script>
	<script src="dashboard/assets/js/app.js"></script>
</body>
</html>